### ISSUE TITLE
Ic2 crash

### ISSUE THREAD

**Issue by TheMajesticPickle** [DimensionalDevelopment/VanillaFix#107] opened 2018-08-12 05:44 UTC
I know I should use the curse release and all, and I will, but I feel like its also important i report the issue anyway just so you're all aware of it; ic2 is incompatible with build 117 (latest), [here](https://paste.dimdev.org/hitozijeta.mccrash) is the report. 

hope this gets fixed, along with all the other incompatibilities

**Comment by Runemoro** [comment] 2018-08-12 13:35
Duplicate of #99 , use the curseforge build for now.

**Closed by Runemoro** 2018-08-12 13:35 UTC
