### ISSUE TITLE
Out of sync error using movement items [1.0.8-72/73dev]

### ISSUE THREAD

**Issue by microcontroling** [DimensionalDevelopment/VanillaFix#59] opened 2018-06-02 17:11 UTC
When using Travel ability in enderio, or double jump on boots(enderio) + Ring of the Flying Squid(basicaly jetpack from extautils) and when falling, player twitches in air. 

[19:57:27] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: Microcontrol out of sync, resyncing! error = 0.0
[19:57:30] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: Microcontrol out of sync, resyncing! error = 2.220446049250313E-16
[19:57:32] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: Microcontrol out of sync, resyncing! error = 0.0
[19:57:32] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: Microcontrol out of sync, resyncing! error = 0.0
[19:58:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: [Microcontrol: Given [The Ender] * 1 to Microcontrol]
[19:58:00] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Given [The Ender] * 1 to Microcontrol

Tested with EnderIO 5.0.25, ExtraUtilities 1.7.6.
Minecraft 1.12.2
VanillaFix 1.0.8-72, 73 dev.

**Comment by Runemoro** [comment] 2018-06-02 17:11
Duplicate of #58. This was fixed for the next release.

**Closed by Runemoro** 2018-06-02 17:11 UTC
