### ISSUE TITLE
"Continue Playing" button sometimes doesn't work (mc.player is null)

### ISSUE THREAD

**Issue by WenXin20** [DimensionalDevelopment/VanillaFix#28] opened 2018-05-18 06:39 UTC
Forge v14.23.3.2862
VanillaFix v1.0.4-35
I tried to load a world that previously worked with v1.0.2, but with this version, I get over 50 crashes at almost the same time. Then pressing the Continue Playing button fails to work. I don't know if it's a mod incompatibility or not. The crash screen just says the mod is unknown.
[Crash Report ](https://paste.dimdev.org/axojazunaj.txt)
[Log](https://gist.github.com/WenXin20/96d178ff5665f34bf1ab80a561cbd49b)

**Comment by P3rf3ctXZer0** [comment] 2018-05-20 23:00
I can confirm this as well. Actually this report has made me realize that this mod is the cause of a massive issue on my server.

**Comment by P3rf3ctXZer0** [comment] 2018-05-21 05:48
Has this been fixed?

**Comment by ZombieHDGaming** [comment] 2018-05-21 05:51
As far as I understand, using worlds that once used an older version of VF doesn't cause an issue. Based on that person's log, something major happened to shift the block IDs by nearly 3,000, so that's an issue with something they did. As for normal issues, I think this should be fine. If you have something different than the OP but similar to it, the logs would be useful.

**Comment by P3rf3ctXZer0** [comment] 2018-05-21 06:15
Um you might need to add support for "NotEnoughIds" by @Fewizz

**Comment by Runemoro** [comment] 2018-05-21 06:17
@P3rf3ctXZer0 The errors are not caused by VanillaFix, in fact, it should be compatible with NotEnoughIds. All that VanillaFix is doing is making a warning about an error in one of your mods, so that you can report it to the developer.

The only VanillaFix bug here is that the "Continue Playing" button isn't working.

**Comment by ZombieHDGaming** [comment] 2018-05-21 06:19
I'm going to be honest here, NEIDs is very much a terribly written coremod and is very much a hacky way of doing it. Words from LexManos himself. This is their issue, not ours

**Comment by Runemoro** [comment] 2018-05-21 06:25
@P3rf3ctXZer0 This is extremely simple to fix and will be fixed in 1.0.6. The "Keep Playing" button not working has nothing to do with NotEnoughIds.

If the NotEnoughIds mod is in fact incompatible (didn't test it but very unlikely), then please report it and I'll try fixing it.

**Comment by P3rf3ctXZer0** [comment] 2018-05-21 06:30
I was referring to the future concurrent task bug.

**Comment by Runemoro** [comment] 2018-05-21 06:32
That's not a bug. Look at your log without VanillaFix, and the error will still be there. VanillaFix is just warning you about it. Disable it in the config and the warning goes away.

**Comment by WenXin20** [comment] 2018-05-21 17:18
The shift in IDs was probably caused when I added new blocks to the config of the Ore Stone Variants mod, which seems to have caused block ID changes.

**Closed** 2018-05-26 09:16 UTC
Labels: bug
