### ISSUE TITLE
[1.12.2] Incompatibility with latest uptade from CubicCHunks

### ISSUE THREAD

**Issue by sa-shiro** [DimensionalDevelopment/VanillaFix#229] opened 2020-02-18 13:14 UTC
VanillaFix is incompatible with the latest update from CubicChunks

https://paste.dimdev.org/tisokoxedu.mccrash

# Working Version:
CubicChunks-1.12.2-0.0.1035.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.115.0-SNAPSHOT-all

# Crashing Version:
CubicChunks-1.12.2-0.0.**1045**.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.**118**.0-SNAPSHOT-all

I was told the issue is with the internals of mixins

## Changelog (CC / CWG)
```
(Feb 18, 2020)
cc1044: Update to mixin 0.8.1
cc1045: Optimized world generation
cwg116: Update to mixin 0.8.1
cwg117: Optimized world generation
cwg118: Mark first commit as version 0.0
 - Barteks2x
```

**Comment by clienthax** [comment] 2020-03-17 20:25
dupe of https://github.com/DimensionalDevelopment/VanillaFix/issues/230

**Comment by BoogieMonster1O1** [comment] 2020-11-10 04:12
Update vanillafix to 1.0.10-150

**Closed by BoogieMonster1O1** 2020-11-10 04:12 UTC
