### ISSUE TITLE
This crash wasn't catch by vanillafix

### ISSUE THREAD

**Issue by forestbat** [DimensionalDevelopment/VanillaFix#76] opened 2018-06-13 05:36 UTC
https://paste.ubuntu.com/p/33QDwGtFfZ/
And why do you removed the idfix of VF？

**Comment by Runemoro** [comment] 2018-06-13 15:19
Duplicate of #73

**Comment by Runemoro** [comment] 2018-06-13 15:19
The id limit fix is being moved to a different mod called JustEnoughIDs, to avoid any bugs related to it from affecting VanillaFix.

**Closed by Runemoro** 2018-06-13 15:19 UTC
