### ISSUE TITLE
1.14 ver?

### ISSUE THREAD

**Issue by thegamerx1** [DimensionalDevelopment/VanillaFix#221] opened 2019-12-10 20:56 UTC
Will this mod get any 1.14 version?

**Comment by S-B99** [comment] 2020-01-22 14:51
Duplicate of #216

**Comment by notspaceuwu** [comment] 2020-09-23 10:35
My issue was opened to better support SpongeForge, not for a mod to be updated to a newer version of Minecraft.

**Comment by BoogieMonster1O1** [comment] 2020-11-10 04:09
This is getting a 1.16 version. Check the 1.16 branch

**Closed by BoogieMonster1O1** 2020-11-10 04:09 UTC
