### ISSUE TITLE
Crash, disabling VanillaFix prevents it from repeating.

### ISSUE THREAD

**Issue by PogoPogoPogo** [DimensionalDevelopment/VanillaFix#23] opened 2018-05-17 01:29 UTC
I'm playing a homemade skyblock pack. Whenever I attempt to mine from my cobblegen the game CTD's. The log can be found [here](https://paste.ee/p/dfEBw). If there is anything I can do to help just let me know. Thanks for your effort so far!

**Comment by Runemoro** [comment] 2018-05-17 05:36
Duplicate of #21

**Closed by Runemoro** 2018-05-17 05:36 UTC
