### ISSUE TITLE
Failed to identify error report

### ISSUE THREAD

**Issue by DWX12** [DimensionalDevelopment/VanillaFix#181] opened 2019-04-19 05:53 UTC
Crash upon trying to load a brand new world. Report said to post it here:

https://paste.dimdev.org/ihetixesod.mccrash

Thanks for all your work guys and let me know if you need more info.

**Comment by Runemoro** [comment] 2019-04-19 07:14
The crash is caused by Random Tweaks. The mod identification not working is a duplicate of #113.

**Closed by Runemoro** 2019-04-19 07:14 UTC

**Comment by DWX12** [comment] 2019-04-20 06:00
Alright thanks, atleast I have an idea of what's going on and where to look.
