### ISSUE TITLE
Block invisible, Buildcraft and logistic pipes

### ISSUE THREAD

**Issue by llronaldoll** [DimensionalDevelopment/VanillaFix#176] opened 2019-04-04 19:26 UTC
the texture of most of the blocks and items in Logistic pipes and Buildcraft do not appear when Vanillafix is ​​added to the modpack

**Comment by Runemoro** [comment] 2019-04-04 20:05
Duplicate of #153

**Closed by Runemoro** 2019-04-04 20:05 UTC
