### ISSUE TITLE
Issue #29 Is still not resolved

### ISSUE THREAD

**Issue by SextupleTap** [DimensionalDevelopment/VanillaFix#32] opened 2018-05-21 15:53 UTC
The glitch was not fixed, as fall distance still does not reset properly (this is not a problem with snow layers as it still happens on ice/normal blocks):

New video(s):

Modded:
https://www.youtube.com/watch?v=5agBLG7TJu4&feature=youtu.be

Vanilla Environment with the mod isolated on its own:
https://www.youtube.com/watch?v=-6Sla_utRq8&feature=youtu.be

VanillaFix version:
VanillaFix-1.0.5-43.jar

Mod Pack:
Custom Pack

MC Version:
1.12.2

Forge Version:
1.12.2-forge1.12.2-14.23.3.2655

Tested Mod Independently:
Yes

**Comment by SextupleTap** [comment] 2018-05-25 01:47
I tried doing a play through in my testing world, apparently the fall damage bug gets exponentially worse the longer you play, eventually the fall damage kept happening so much it would keep happening in quick successions while in mid air or every time you hit the ground consecutively a few times in a row, I did not die because I gave myself resistance 2 and saturation for an infinite duration.

Eventually the fall damage happens more often, back to back more often, and in larger damage amounts. My testing ultimate came to an end when a single fall damage incident that should not have happened one shot me, yes I repeat, the random fall damage tick bug ended up one hit killing me at some point. Also the same bug where dying crashes your game is happening again...

**Comment by ZombieHDGaming** [comment] 2018-05-25 01:50
We are trying to figure out how to fix the fall damage bug. Rune and I have been kinda busy the past few days so code pushes have been scarce. But I will say, the dying crashes your game bug is new to me. Mind telling me more about it, or possibly providing a log from that?

**Comment by SextupleTap** [comment] 2018-05-25 16:19
@ZombieHDGaming and @Runemoro I was able to find the crash-log related to the "crashing on player dying" bug.

Paste of the log:
https://paste.dimdev.org/quvilebexu.sql

I do believe this could be a "random occurrence" that can randomly happen on game startup or world creation, or it could be a mod incompatibility.

**Comment by ZombieHDGaming** [comment] 2018-05-25 16:44
@SextupleTap I think it might be safe to say that that issue is caused by Headcrumbs by the looks of it, considering this is in the second line of the crash log:
```java
at ganymedes01.headcrumbs.eventHandlers.HandlerEvents.playerDrop(HandlerEvents.java:83)
```
It looks like Headcrumbs doesn't like what we're doing to the EnchantmentHelper. Considering Headcrumbs is still very much alpha for 1.12 due to it missing very key aspects and various features that makes Headcrumbs Headcrumbs, I'd suggest you just remove it for now.

**Comment by SextupleTap** [comment] 2018-05-25 18:13
@ZombieHDGaming the game has stopped doing the crashing part after uninstalling headcrumbs. Would it be useful to reference this to the headcrumbs developer(s), or is this something that you two can fix yourselves?

**Comment by ZombieHDGaming** [comment] 2018-05-25 18:16
I'd make an issue with Turkey's repo about it since they should look into that, and also probably finish the mod for a full release.

**Comment by SextupleTap** [comment] 2018-05-25 20:31
Alright, sounds good!

Now all that is left is that supper strange and pesky fall damage bug...

**Comment by Runemoro** [comment] 2018-05-26 09:13
Fixed in latest dev build.

**Closed by Runemoro** 2018-05-26 09:13 UTC
Labels: bug
