### ISSUE TITLE
unable to dowload

### ISSUE THREAD

**Issue by aadityathegreat** [DimensionalDevelopment/VanillaFix#313] opened 2021-04-06 15:57 UTC
you cant go to the curseforge page to download it,and there are no other ways to get the link to download to my knowledge,would be helpful if you have other websites to download from

**Comment by ZombieHDGaming** [comment] 2021-04-06 16:13
Just went to CurseForge and did a test download, the jar files seem to be working as intended and are downloading. As for downloading from other websites, we only trust CurseForge, potentially Modrinth in the future, our GitHub releases, and that's about it currently. Either way, downloading is working, so closing this.

**Closed as completed by ZombieHDGaming** 2021-04-06 16:13 UTC
