### ISSUE TITLE
NoClassDefFoundError: Could not initialize org.dimdev.vanillafix.textures.ModCompatibility 

### ISSUE THREAD

**Issue by Hypsellis** [DimensionalDevelopment/VanillaFix#61] opened 2018-06-02 19:14 UTC
I come back with this crash because it still happens to me. I use Forge 14.23.4.2707. Here is the crash report and log.
https://pastebin.com/LD9hJUzP
https://pastebin.com/utv8eE8W

**Comment by Runemoro** [comment] 2018-06-02 19:18
Duplicate of #48

**Closed by Runemoro** 2018-06-02 19:18 UTC

**Comment by Hypsellis** [comment] 2018-06-02 19:26
I don't use Thaumic Additions

**Comment by Runemoro** [comment] 2018-06-02 19:27
The issue happens with a few mods. The title includes Thaumic Additions because it's one of them, just to know how to reproduce the issue.
