### ISSUE TITLE
VanillaFix cause codechicken-lib crash

### ISSUE THREAD

**Issue by MoeShimaKaze** [DimensionalDevelopment/VanillaFix#95] opened 2018-07-12 05:04 UTC
codechicken-lib Version:1.12.2-3.2.0.345-universal
VanillaFix Version:VanillaFix-1.0.10-107
Forge Version:1.12.2-14.23.4.2705
Mod list:https://pastebin.com/Zsf5A1wL
Crash-report:https://paste.dimdev.org/avojimogen.mccrash

**Comment by Robijnvogel** [comment] 2018-07-12 08:55
Could you check if this also happens without Optifine installed?

**Comment by MoeShimaKaze** [comment] 2018-07-12 10:49
OK，i will try it

**Comment by MoeShimaKaze** [comment] 2018-07-12 11:01
without OptiFine,the cilent don't crash
i think the problem is OptiFine or VanillaFix's problem
so can you fix it?

**Comment by Runemoro** [comment] 2018-07-12 11:42
Duplicate of #93

**Closed by Runemoro** 2018-07-12 11:42 UTC
