### ISSUE TITLE
Crash when disabling texture fixes since I use optifine

### ISSUE THREAD

**Issue by TheRealDadbeard** [DimensionalDevelopment/VanillaFix#109] opened 2018-08-22 07:35 UTC
https://hastebin.com/tapiborese.rb

**Comment by TheSnowyChickens** [comment] 2018-08-23 02:00
I don't have Optifine installed and get a crash from Tinkers. (https://paste.dimdev.org/epaqocifuk.mccrash)

**Comment by ZombieHDGaming** [comment] 2018-08-23 02:05
This is apparently an issue between VF and the new FoamFix version. I'd suggest rolling back either a version or 2 for the moment. I think FoamFix has only added one fix, which is something I will add this weekend alongside possibly updating to 1.13.

**Comment by TheSnowyChickens** [comment] 2018-08-23 02:25
Then I can close my issue to this crash on the Tinkers Github? :D

**Comment by ZombieHDGaming** [comment] 2018-08-23 02:26
Umm, sure? Go for it

**Comment by MasterEnderman** [comment] 2018-08-23 11:50
The Crash also occurs without foamfix installed.
https://paste.dimdev.org/ajuvugeson.mccrash

**Comment by Runemoro** [comment] 2019-01-04 16:04
The crash without FoamFix when disabling texture fixes was fixed a while ago. The crash with FoamFix is a duplicate of #110 .

**Closed by Runemoro** 2019-01-04 16:04 UTC
Labels: dev version issue
