### ISSUE TITLE
Thermal Expansion not rendering

### ISSUE THREAD

**Issue by ESTD3** [DimensionalDevelopment/VanillaFix#166] opened 2019-01-07 16:17 UTC
Using latest VanillaFix which is currently version: VanillaFix-1.1.1-132.jar
Forge: 2806
Thermal Expansion: 5.5.2.39-universal
Optifine: OptiFine 1.12.2 HD U E3
Foamfix: 0.10.3

Thermal Expansion machines, items do not render(show totally opaque) or have pink large textures. Hope these rendering issues get solved as soon as possible because it is impossible to play with non existing textures or invisible textures, which is even more annoying.

**Comment by Runemoro** [comment] 2019-01-08 13:43
Duplicate of #153

**Closed by Runemoro** 2019-01-08 13:43 UTC
