### ISSUE TITLE
Duplicate mod on server with Forge >2655

### ISSUE THREAD

**Issue by GreyMamoN** [DimensionalDevelopment/VanillaFix#1] opened 2018-04-26 16:41 UTC
```net.minecraftforge.fml.common.DuplicateModsFoundException: 
Duplicate Mods:
	vanillafix : /home/grey/MCSRV/1.12.2/./mods/VanillaFix-1.0.0-1.jar
	vanillafix : /home/grey/MCSRV/1.12.2/./mods/VanillaFix-1.0.0-1.jar
```

**Comment by Runemoro** [comment] 2018-04-26 19:47
I'm not able to reproduce this issue. This happens on startup, or did you do something special? What version of forge are you using? Does this also happen with only VanillaFix installed?

**Comment by Dalethium** [comment] 2018-04-26 21:37
I have the same issue, [Crash Report](https://pastebin.com/MyR40Equ)

**Comment by Runemoro** [comment] 2018-04-26 21:47
@Dalethium Does it only happen on the server, or also the client?

**Comment by Dalethium** [comment] 2018-04-27 01:13
Just tested,  the client works fine.

**Comment by ZombieHDGaming** [comment] 2018-04-27 01:15
@Dalethium Thanks for the confirmation. Rune and I will look into what is causing this and will hopefully be in the next dev build

**Comment by Runemoro** [comment] 2018-04-27 21:41
@Dalethium Does the issue happen with only VanillaFix installed for you? I'm not able to reproduce it. If yes, what forge version are you using? If not, then could you try to find which mod breaks it, or send me a zip of your mods if you don't have time?

**Comment by Dalethium** [comment] 2018-04-28 23:55
@Runemoro Sorry I did not see your post! [Here's my mods](https://mega.nz/#!ioIADRza!hWeXekDg1VrPgsAPMEb6Etr-mbtxUgaQ7eRvmEZHM-Y)

I took the time to sort them into folders according to which side they are installed on.

**Comment by Runemoro** [comment] 2018-04-28 23:58
Thanks, but I found the problem. Use forge recommended (2655) until either I fix it or Forge fixes it.

**Comment by Sunconure11** [comment] 2018-05-05 15:34
Tell me when a build with the fix comes out, as I'm encountering it too. It seems a lot of the newer builds of Forge are incompatible with lots of things

https://pastebin.com/f1jm1rYn

**Comment by Runemoro** [comment] 2018-05-05 15:35
@Sunconure11 https://github.com/DimensionalDevelopment/VanillaFix/releases/latest

**Comment by Sunconure11** [comment] 2018-05-05 15:37
Any plans to publish that build to curse?

**Comment by Runemoro** [comment] 2018-05-05 15:38
After I fix a few other bugs

**Comment by Sunconure11** [comment] 2018-05-05 15:38
Alright

**Comment by Runemoro** [comment] 2018-05-11 00:52
Unfortunately, the fix for this causes the mod to not be loaded at all. Reopening this until https://github.com/SpongePowered/Mixin/issues/253 is fixed.

**Comment by ZombieHDGaming** [comment] 2018-05-11 17:30
After some investigation, I think I've solved this issue once and for all. Until Rune and I can get the ModIdentification fixed, however, the mod will not run on a server yet due to errors. This will be Rune and myself's next issue to fix.

**Closed** 2018-05-11 19:50 UTC
Labels: Caused By Dependency, Fixed In Dev
