### ISSUE TITLE
Sprint Jumping in a 2 tall area

### ISSUE THREAD

**Issue by SextupleTap** [DimensionalDevelopment/VanillaFix#63] opened 2018-06-03 18:57 UTC
Sprint jumping in a 2 tall area whether it be under a tree, or on ice so that you move much faster snaps you back and slows you down when it shouldn't. This is easily to self replicate and is from version 1.07

**Comment by Runemoro** [comment] 2018-06-03 18:59
Duplicate of #58, use the latest dev build for a fix

**Closed by Runemoro** 2018-06-03 18:59 UTC
