### ISSUE TITLE
Landed Ender Dragon can still hurts entities

### ISSUE THREAD

**Issue by Ghostrider231** [DimensionalDevelopment/VanillaFix#14] opened 2018-05-11 08:21 UTC
Minecraft Version: 1.12.2
Forge Version: 14.23.3.2680

In **vanilla**, the Ender Dragon doesn't cause any damage or fling entities while it's doing it's "landed" mode.

While having this mod installed. (Even only this)
-
When trying to fight the Ender Dragon while in it's "landed" mode , it can still damage entites. (You can even witness the endermen getting hurt by the Dragon while it's landed)

If you attempt to get closer to the "Landed" Ender Dragon, you'll get flunged like a couple hundred blocks away. (This is mostly noticeable in creative)

The hit-box for the Ender Dragon also feels a little janky with this installed, but i think that's just me. (I assume)

**Comment by ZombieHDGaming** [comment] 2018-05-11 15:30
That's rather odd......we don't even touch anywhere near the Ender Dragon code. I'll do some testing, but that is really odd.

**Comment by Runemoro** [comment] 2018-05-26 19:03
We're not able to reproduce this issue, or I fixed it without realizing. The landed ender dragon hurts entities in vanilla too.

**Closed by Runemoro** 2018-05-26 19:03 UTC
Labels: invalid
